# Generated by Django 6.0 on 2025-12-29 00:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_submission_student_user_studentprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='section',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='University ID must contain digits only', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='university_id',
            field=models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='University ID must contain digits only', regex='^\\d+$')]),
        ),
        migrations.CreateModel(
            name='SubjectFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('teacher', 'name')},
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='quizzes.subjectfolder'),
        ),
    ]
