# Generated by Django 5.2.10 on 2026-01-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_alter_studentprofile_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='city',
            field=models.CharField(choices=[('Riyadh', 'Riyadh'), ('Jeddah', 'Jeddah'), ('Dammam', 'Dammam'), ('Al-Ahsa', 'Al-Ahsa'), ('Medina', 'Medina'), ('Hail', 'Hail')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='major',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('IT', 'Information Technology'), ('BUS', 'Business'), ('LS', 'Language Studies')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('submission', 'question')},
        ),
    ]
