# Generated by Django 5.2.10 on 2026-01-20 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_quiz_due_at_quiz_duration_seconds_quiz_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='duration_seconds',
            new_name='duration_minutes',
        ),
    ]
