# Generated by Django 5.2.10 on 2026-02-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0007_alter_answer_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='city',
            field=models.CharField(choices=[('Riyadh', 'Riyadh'), ('Jeddah', 'Jeddah'), ('Dammam', 'Dammam'), ('Al-Ahsa', 'Al-Ahsa'), ('Hail', 'Hail'), ('Madinah', 'Madinah')], max_length=30),
        ),
    ]
