# Generated by Django 5.2.10 on 2026-02-03 16:28

import quizzes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0010_filesubmission_question_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesubmission',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filesubmission',
            name='teacher_file',
            field=models.FileField(blank=True, null=True, upload_to=quizzes.models.teacher_feedback_upload_path),
        ),
        migrations.AddField(
            model_name='filesubmission',
            name='teacher_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
