# Generated by Django 5.2.10 on 2026-02-03 19:03

import quizzes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0011_filesubmission_graded_at_filesubmission_teacher_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='manual_grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='teacher_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='teacher_file',
            field=models.FileField(blank=True, null=True, upload_to=quizzes.models.teacher_feedback_file_path),
        ),
        migrations.AddField(
            model_name='submission',
            name='teacher_file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
